version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-app-postgres
    environment:
      POSTGRES_DB: todoapp_local
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp_local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: